---
roles:
  - name: aheimsbakk.restic_backup
    version: '1.2.1'
  - name: aheimsbakk.libvirt_provision
    src: https://github.com/aheimsbakk/ansible-role-libvirt-provision.git
    scm: git
    version: '1.0.0'

collections:
  - name: containers.podman
    version: ">=1.18.0,<=2.0.0"
  - name: community.general
    version: ">=12.0.0,<=13.0.0"
  - name: ansible.posix
    version: ">=2.1.0,<=3.0.0"
  - name: community.libvirt
    version: ">=2.0.0,<=3.0.0"
